name: Setup a Tor Bridge

on:
  workflow_dispatch:

jobs:
  setup-tor-bridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tor
        run: |
          sudo apt update
          sudo apt install tor
      - name: Install obfs4proxy
        run: sudo apt-get install obfs4proxy
      - name: Get VMs public IP
        id: ip
        uses: haythem/public-ip@v1.3
      - name: Copy torrc file
        run: |
          sudo rm /etc/tor/torrc
          sudo cp ./torrc /etc/tor/
      - name: Change service file details
        run: |
          sudo sed -i 's/NoNewPrivileges=yes/NoNewPrivileges=no/' /lib/systemd/system/tor@default.service
          sudo sed -i 's/NoNewPrivileges=yes/NoNewPrivileges=no/' /lib/systemd/system/tor@.service
          sudo systemctl daemon-reload
      - name: Start Tor
        run: sudo systemctl enable --now tor.service
      - name: Print bridge line for manual connection
        run: sudo cat /var/lib/tor/pt_state/obfs4_bridgeline.txt
      - name: View logs
        run: sudo journalctl -e -u tor@default
      - name: keepalive
        run: while true; do echo "keepalive"; sleep 10; done
